# SPDX-FileCopyrightText: 2025 Arcangelo Massari <info@arcangelomassari.com>
#
# SPDX-License-Identifier: ISC

arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart