name: Release

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  check-release-trigger:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      should-release: ${{ steps.check.outputs.should-release }}
      commit-message: ${{ steps.check.outputs.commit-message }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Check for release trigger
      id: check
      run: |
        # Ottieni il messaggio del commit più recente
        COMMIT_MSG=$(git log --format=%B -n 1 ${{ github.event.workflow_run.head_sha }})
        echo "commit-message=$COMMIT_MSG" >> $GITHUB_OUTPUT
        echo "Commit message: $COMMIT_MSG"
        
        # Controlla se contiene [release] tra parentesi quadre
        if [[ "$COMMIT_MSG" =~ \[release\] ]]; then
          echo "Release trigger found in commit message"
          echo "should-release=true" >> $GITHUB_OUTPUT
        else
          echo "No release trigger found"
          echo "should-release=false" >> $GITHUB_OUTPUT
        fi

  release:
    runs-on: ubuntu-latest
    needs: check-release-trigger
    if: needs.check-release-trigger.outputs.should-release == 'true'
    outputs:
      version: ${{ steps.semantic.outputs.new-release-version }}
      released: ${{ steps.semantic.outputs.new-release-published }}
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install semantic-release
      run: |
        npm install -g semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github
    
    - name: Run semantic-release
      id: semantic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npx semantic-release --dry-run=false

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [check-release-trigger, release]
    if: needs.release.outputs.released == 'true'
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.2'
        channel: 'stable'
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Update pubspec.yaml version
      run: |
        VERSION="${{ needs.release.outputs.version }}"
        # Aggiorna la versione nel pubspec.yaml
        sed -i "s/^version: .*/version: $VERSION+${{ github.run_number }}/" pubspec.yaml
        echo "Updated pubspec.yaml to version $VERSION+${{ github.run_number }}"
    
    - name: Install Linux dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
    
    - name: Enable Linux desktop
      run: flutter config --enable-linux-desktop
    
    - name: Build web release
      run: |
        flutter build web --release --base-href /portfolio/ --dart-define=FLUTTER_WEB_CANVASKIT_URL=https://www.gstatic.com/flutter-canvaskit/
        cd build/web
        zip -r ../../portfolio-web-${{ needs.release.outputs.version }}.zip .
        cd ../..
    
    - name: Build Linux release
      run: |
        flutter build linux --release
        cd build/linux/x64/release/bundle
        tar -czf ../../../../../portfolio-linux-${{ needs.release.outputs.version }}.tar.gz .
        cd ../../../../../
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ needs.release.outputs.version }}
        name: Release v${{ needs.release.outputs.version }}
        body_path: CHANGELOG.md
        files: |
          portfolio-web-${{ needs.release.outputs.version }}.zip
          portfolio-linux-${{ needs.release.outputs.version }}.tar.gz
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Cleanup artifacts
      run: |
        rm -f portfolio-web-${{ needs.release.outputs.version }}.zip
        rm -f portfolio-linux-${{ needs.release.outputs.version }}.tar.gz